### ISSUE TITLE
'Christian Online School' link under Sponsors is a bad link

### ISSUE THREAD

**Issue by willbprog127** [ghostbsd/ghostbsd.org#2]
On pages which show the small Sponsors links, 'Christian Online School' is pointing to _http://ghostbsd.org/www.northgateacademy.com_ instead of _www.northgateacademy.com_

Thanks! :+1:

**Comment by ericbsd** [comment]
Thanks for pointing that to us

**Comment by ericbsd** [comment]
resolve

**Comment by willbprog127** [comment]
Thank you! :smile:
