### ISSUE TITLE
GhostBSD ISO checksum incorrect on Downloads page

### ISSUE THREAD

**Issue by willbprog127** [ghostbsd/ghostbsd.org#3]
Directly under the 64-bit direct download link for the official release on the Downloads page, the sha256sum is incorrect (73e1c7589a8de8ce8c9d981dbb19c56fd22286a4d776eb1a938d3a9926761e58) when the actual link to the GhostBSD-20.08.04.iso.sha256 _is_ correct (5b7e496564c6f9879061a9620774ae937c0ac73ea5ed4b304da9b267b2f6e468).

Thanks :smiley:

**Comment by ericbsd** [comment]
Oops my fault, thanks for reporting I will fix that right away.

**Comment by ericbsd** [comment]
Fix
