### ISSUE TITLE
System requirements: memory/RAM

### ISSUE THREAD

**Issue by grahamperrin** [ghostbsd/ghostbsd.org#4]
https://www.ghostbsd.org/download describes:

> 4 GB of RAM

– as a _minimum_. 

Alongside the minimium requirements, it may be helpful to describe what's _recommended_ for booting from the `.iso`; and to explain that not so much is required for installed systems (without the `.iso`). 

From <https://forums.ghostbsd.org/viewtopic.php?p=8803#p8803> (2020-12-03): 

> The recommended ram for the new iso is 6GB under that we can't say it will be stable.

**Comment by ericbsd** [comment]
4 GB of RAM is the requirement to boot the ISO!

>From https://forums.ghostbsd.org/viewtopic.php?p=8803#p8803 (2020-12-03):

The forum post is an old requirement

**Comment by grahamperrin** [comment]
Partly relating to https://forums.ghostbsd.org/viewtopic.php?p=9425#p9425 (VirtualBox on a late 2008 MacBook Pro with 8 GB memory), I was curious about how GhostBSD would perform with _very_ little memory given to a guest machine. 

Two screenshots from 3rd May – FreeBSD `14.0-CURRENT` host, GhostBSD `13-RELEASE` with VirtualBox in seamless mode on the display to the left: 

![2021-05-03 07:12:51 GhostBSD 13-RELEASE with 1 GB memory](https://user-images.githubusercontent.com/192271/117565167-c705b880-b0a7-11eb-8055-4b622a8ec467.png)

![2021-05-03 07:15:35 GhostBSD 13-RELEASE with 1 GB memory, Element](https://user-images.githubusercontent.com/192271/117565182-d1c04d80-b0a7-11eb-8c2d-0142f04679cb.png)

_Functional_ with `1 GB` memory, however I should say that it is **essential** to have a reasonably large swap partition. For the experiment above, I set `8` when installing GhostBSD. 

----

Experiments aside: for real-world use, I normally have swap partitions no smaller than 16 GB. YMMV, I understand that sizes are debatable.

**Comment by ericbsd** [comment]
After going back and forth with this issue, the initial reason was to stop dealing with old hardware. I do not think that we should clarify why when I do not want to deal with old hardware. For those who want to live in the past, they can install FreeBSD.
